<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5c194780ce619',
	'title' => 'Page Builder',
	'fields' => array(
		array(
			'key' => 'field_5c810b1366633',
			'label' => 'Show Content',
			'name' => 'show_content',
			'type' => 'true_false',
			'instructions' => 'Show the main content on the page when page builder is active',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5ca37b357be31',
			'label' => 'Content Container',
			'name' => 'content_contained',
			'type' => 'true_false',
			'instructions' => 'Use the global container width for the main content',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c810b1366633',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c59f3fca6250',
			'label' => 'Page Sections',
			'name' => 'sections',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5c194d7dc7992',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Section',
			'sub_fields' => array(
				array(
					'key' => 'field_5c194d7dc7992',
					'label' => 'Page Section',
					'name' => 'page_section',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c5a04b23727f',
							'label' => 'Section Blocks',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5c55bd9b11eb5',
							'label' => 'Blocks',
							'name' => 'block_selection',
							'type' => 'flexible_content',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layouts' => array(
								'5c55bdadb79b3' => array(
									'key' => '5c55bdadb79b3',
									'name' => 'content_block_layout',
									'label' => 'Content Block',
									'display' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5c59efc901e71',
											'label' => 'Content Block',
											'name' => 'content_block',
											'type' => 'group',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'layout' => 'block',
											'sub_fields' => array(
												array(
													'key' => 'field_5c632a47251b3',
													'label' => 'Block Content',
													'name' => '',
													'type' => 'tab',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'placement' => 'top',
													'endpoint' => 0,
												),
												array(
													'key' => 'field_5c59efc901e74',
													'label' => 'Content',
													'name' => 'content',
													'type' => 'wysiwyg',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'tabs' => 'all',
													'toolbar' => 'full',
													'media_upload' => 1,
													'delay' => 0,
												),
												array(
													'key' => 'field_5c632a7b251b4',
													'label' => 'Block Settings',
													'name' => '',
													'type' => 'tab',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'placement' => 'top',
													'endpoint' => 0,
												),
												array(
													'key' => 'field_5c59efc901e72',
													'label' => 'ID',
													'name' => 'block_id',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_5c59efc901e73',
													'label' => 'Classes',
													'name' => 'block_class',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_5c5dc3bb6feea',
													'label' => 'Width',
													'name' => 'block_width',
													'type' => 'range',
													'instructions' => 'width in columns',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'min' => '',
													'max' => 12,
													'step' => 1,
													'prepend' => '',
													'append' => '',
												),
												array(
													'key' => 'field_5c5dc4366feeb',
													'label' => 'Vertical Alignment',
													'name' => 'v_align',
													'type' => 'select',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'choices' => array(
														'top' => 'top',
														'middle' => 'middle',
														'bottom' => 'bottom',
													),
													'default_value' => array(
													),
													'allow_null' => 1,
													'multiple' => 0,
													'ui' => 1,
													'ajax' => 0,
													'return_format' => 'value',
													'placeholder' => '',
												),
												array(
													'key' => 'field_5c822ecf44ce7',
													'label' => 'Center Content',
													'name' => 'center_content',
													'type' => 'true_false',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'message' => '',
													'default_value' => 0,
													'ui' => 1,
													'ui_on_text' => '',
													'ui_off_text' => '',
												),
											),
										),
									),
									'min' => '',
									'max' => '',
								),
								'layout_5c59d18c5a744' => array(
									'key' => 'layout_5c59d18c5a744',
									'name' => 'image_block_layout',
									'label' => 'Image Block',
									'display' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5c59d18c5a746',
											'label' => 'Image Block',
											'name' => 'image_block',
											'type' => 'group',
											'instructions' => 'width in columns',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'layout' => 'block',
											'sub_fields' => array(
												array(
													'key' => 'field_5c6329fd251b2',
													'label' => 'Block Content',
													'name' => '',
													'type' => 'tab',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'placement' => 'top',
													'endpoint' => 0,
												),
												array(
													'key' => 'field_5c59d18c5a749',
													'label' => 'Image',
													'name' => 'image',
													'type' => 'image',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '30',
														'class' => '',
														'id' => '',
													),
													'return_format' => 'array',
													'preview_size' => 'thumbnail',
													'library' => 'all',
													'min_width' => '',
													'min_height' => '',
													'min_size' => '',
													'max_width' => '',
													'max_height' => '',
													'max_size' => '',
													'mime_types' => 'jpg,png,gif',
												),
												array(
													'key' => 'field_5c6050d7c5edc',
													'label' => 'Image Text',
													'name' => 'caption',
													'type' => 'wysiwyg',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '70',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'tabs' => 'all',
													'toolbar' => 'full',
													'media_upload' => 0,
													'delay' => 0,
												),
												array(
													'key' => 'field_5c6329a02c9e5',
													'label' => 'Block Settings',
													'name' => '',
													'type' => 'tab',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'placement' => 'top',
													'endpoint' => 0,
												),
												array(
													'key' => 'field_5c59d18c5a747',
													'label' => 'ID',
													'name' => 'block_id',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => 30,
												),
												array(
													'key' => 'field_5c59d18c5a748',
													'label' => 'Classes',
													'name' => 'block_class',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_5c5dc4e86feec',
													'label' => 'Width',
													'name' => 'block_width',
													'type' => 'range',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'min' => '',
													'max' => 12,
													'step' => 1,
													'prepend' => '',
													'append' => '',
												),
												array(
													'key' => 'field_5c6336352d220',
													'label' => 'Full Height',
													'name' => 'img_full_height',
													'type' => 'true_false',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'message' => '',
													'default_value' => 0,
													'ui' => 1,
													'ui_on_text' => '',
													'ui_off_text' => '',
												),
												array(
													'key' => 'field_5c633ab71af4f',
													'label' => 'Image Size',
													'name' => 'image_size',
													'type' => 'select',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'choices' => array(
														'thumbnail' => 'Thumbnail',
														'medium' => 'Medium',
														'large' => 'Large',
														'full' => 'Full',
													),
													'default_value' => array(
														0 => 'large',
													),
													'allow_null' => 1,
													'multiple' => 0,
													'ui' => 1,
													'ajax' => 0,
													'return_format' => 'value',
													'placeholder' => '',
												),
												array(
													'key' => 'field_5c5dc5076feed',
													'label' => 'Vertical Alignment',
													'name' => 'v_align',
													'type' => 'select',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'choices' => array(
														'top' => 'top',
														'middle' => 'middle',
														'bottom' => 'bottom',
													),
													'default_value' => array(
													),
													'allow_null' => 1,
													'multiple' => 0,
													'ui' => 1,
													'ajax' => 0,
													'return_format' => 'value',
													'placeholder' => '',
												),
												array(
													'key' => 'field_5c609c2adfcba',
													'label' => 'Image Height',
													'name' => 'image_height',
													'type' => 'number',
													'instructions' => 'height in px',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'min' => '',
													'max' => '',
													'step' => '',
												),
												array(
													'key' => 'field_5c606a875217c',
													'label' => 'Image as Background',
													'name' => 'img_as_bg',
													'type' => 'true_false',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'message' => '',
													'default_value' => 0,
													'ui' => 1,
													'ui_on_text' => '',
													'ui_off_text' => '',
												),
												array(
													'key' => 'field_5c61de4582a73',
													'label' => 'Image Overlay',
													'name' => 'img_overlay',
													'type' => 'true_false',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => array(
														array(
															array(
																'field' => 'field_5c606a875217c',
																'operator' => '==',
																'value' => '1',
															),
														),
													),
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'message' => '',
													'default_value' => 0,
													'ui' => 1,
													'ui_on_text' => '',
													'ui_off_text' => '',
												),
												array(
													'key' => 'field_5c61de9782a74',
													'label' => 'Overlay Colour',
													'name' => 'overlay_color',
													'type' => 'color_picker',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => array(
														array(
															array(
																'field' => 'field_5c61de4582a73',
																'operator' => '==',
																'value' => '1',
															),
														),
													),
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => 'rgba(0,0,0,.4)',
												),
												array(
													'key' => 'field_5c61dee682a75',
													'label' => 'Text Colour',
													'name' => 'text_color',
													'type' => 'color_picker',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => array(
														array(
															array(
																'field' => 'field_5c606a875217c',
																'operator' => '==',
																'value' => '1',
															),
														),
													),
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
												),
											),
										),
									),
									'min' => '',
									'max' => '',
								),
								'layout_5cb5e9a233233' => array(
									'key' => 'layout_5cb5e9a233233',
									'name' => 'tabs_block_layout',
									'label' => 'Tabs Block',
									'display' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5cb5e9d533234',
											'label' => 'Tabs Block',
											'name' => 'tabs_block',
											'type' => 'group',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'layout' => 'block',
											'sub_fields' => array(
												array(
													'key' => 'field_5cb5ee9e4158b',
													'label' => 'Block Content',
													'name' => '',
													'type' => 'tab',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'placement' => 'top',
													'endpoint' => 0,
												),
												array(
													'key' => 'field_5cb5f81b6bd7a',
													'label' => 'Tab',
													'name' => 'tab',
													'type' => 'repeater',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'collapsed' => '',
													'min' => 1,
													'max' => 0,
													'layout' => 'table',
													'button_label' => 'Add tab',
													'sub_fields' => array(
														array(
															'key' => 'field_5cb5eecf4158c',
															'label' => 'Tab Title',
															'name' => 'block_title',
															'type' => 'text',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'default_value' => '',
															'placeholder' => '',
															'prepend' => '',
															'append' => '',
															'maxlength' => '',
														),
														array(
															'key' => 'field_5cb5ef034158d',
															'label' => 'Tab Content',
															'name' => 'block_content',
															'type' => 'wysiwyg',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'default_value' => '',
															'tabs' => 'all',
															'toolbar' => 'full',
															'media_upload' => 1,
															'delay' => 0,
														),
													),
												),
												array(
													'key' => 'field_5cb5ef144158e',
													'label' => 'Block Settings',
													'name' => '',
													'type' => 'tab',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'placement' => 'top',
													'endpoint' => 0,
												),
												array(
													'key' => 'field_5cb5ecd779129',
													'label' => 'Block ID',
													'name' => 'block_id',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_5cb5ece77912a',
													'label' => 'Block Class',
													'name' => 'block_class',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_5cb5ef5b41591',
													'label' => 'Block Width',
													'name' => 'block_width',
													'type' => 'range',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'min' => 0,
													'max' => 12,
													'step' => '',
													'prepend' => '',
													'append' => '',
												),
												array(
													'key' => 'field_5cb8254bebbc5',
													'label' => 'Accordion',
													'name' => 'accordion',
													'type' => 'true_false',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'message' => '',
													'default_value' => 0,
													'ui' => 1,
													'ui_on_text' => '',
													'ui_off_text' => '',
												),
												array(
													'key' => 'field_5cb73f15c59c1',
													'label' => 'Block Height',
													'name' => 'block_height',
													'type' => 'number',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => array(
														array(
															array(
																'field' => 'field_5cb8254bebbc5',
																'operator' => '!=',
																'value' => '1',
															),
														),
													),
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'min' => 1500,
													'max' => '',
													'step' => 1,
												),
												array(
													'key' => 'field_5cb73c735fbb5',
													'label' => 'Center Content',
													'name' => 'center_content',
													'type' => 'true_false',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => array(
														array(
															array(
																'field' => 'field_5cb8254bebbc5',
																'operator' => '!=',
																'value' => '1',
															),
														),
													),
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'message' => '',
													'default_value' => 0,
													'ui' => 1,
													'ui_on_text' => '',
													'ui_off_text' => '',
												),
											),
										),
									),
									'min' => '',
									'max' => '',
								),
								'layout_5cbeca99659bd' => array(
									'key' => 'layout_5cbeca99659bd',
									'name' => 'gallery_block_layout',
									'label' => 'Gallery',
									'display' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5cbecc07dc859',
											'label' => 'Gallery Block',
											'name' => 'gallery_block',
											'type' => 'group',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'layout' => 'block',
											'sub_fields' => array(
												array(
													'key' => 'field_5cbecc08dc85a',
													'label' => 'Block Content',
													'name' => '',
													'type' => 'tab',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'placement' => 'top',
													'endpoint' => 0,
												),
												array(
													'key' => 'field_5cbecc35dc862',
													'label' => 'Gallery',
													'name' => 'gallery',
													'type' => 'gallery',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'min' => '',
													'max' => '',
													'insert' => 'append',
													'library' => 'all',
													'min_width' => '',
													'min_height' => '',
													'min_size' => '',
													'max_width' => '',
													'max_height' => '',
													'max_size' => '',
													'mime_types' => '',
												),
												array(
													'key' => 'field_5cbecc08dc85c',
													'label' => 'Block Settings',
													'name' => '',
													'type' => 'tab',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'placement' => 'top',
													'endpoint' => 0,
												),
												array(
													'key' => 'field_5cbecc08dc85d',
													'label' => 'ID',
													'name' => 'block_id',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_5cbecc08dc85e',
													'label' => 'Classes',
													'name' => 'block_class',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_5cbecc08dc85f',
													'label' => 'Width',
													'name' => 'block_width',
													'type' => 'range',
													'instructions' => 'width in columns',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'min' => '',
													'max' => 12,
													'step' => 1,
													'prepend' => '',
													'append' => '',
												),
												array(
													'key' => 'field_5cbef5aad7bfb',
													'label' => 'Columns',
													'name' => 'columns',
													'type' => 'range',
													'instructions' => 'Images per row',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => 4,
													'min' => 1,
													'max' => 6,
													'step' => 1,
													'prepend' => '',
													'append' => '',
												),
												array(
													'key' => 'field_5cbecc08dc860',
													'label' => 'Image Size',
													'name' => 'image_size',
													'type' => 'select',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'choices' => array(
														'thumbnail' => 'Thumbnail',
														'medium' => 'Medium',
														'large' => 'Large',
														'full' => 'Full',
													),
													'default_value' => array(
													),
													'allow_null' => 1,
													'multiple' => 0,
													'ui' => 1,
													'ajax' => 0,
													'return_format' => 'value',
													'placeholder' => '',
												),
												array(
													'key' => 'field_5cbf0a100776b',
													'label' => 'Image Height',
													'name' => 'image_height',
													'type' => 'number',
													'instructions' => 'Height of each image',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => 'px',
													'min' => '',
													'max' => '',
													'step' => '',
												),
												array(
													'key' => 'field_5cbf3051fd06e',
													'label' => 'Show Captions',
													'name' => 'show_captions',
													'type' => 'true_false',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'message' => '',
													'default_value' => 1,
													'ui' => 1,
													'ui_on_text' => '',
													'ui_off_text' => '',
												),
											),
										),
									),
									'min' => '',
									'max' => '',
								),
								'layout_5cc855105bab4' => array(
									'key' => 'layout_5cc855105bab4',
									'name' => 'plain_text_block_layout',
									'label' => 'Plain Text Block',
									'display' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5cc855105bab5',
											'label' => 'Plain Text Block',
											'name' => 'plain_text_block',
											'type' => 'group',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'layout' => 'block',
											'sub_fields' => array(
												array(
													'key' => 'field_5cc855105bab6',
													'label' => 'Block Content',
													'name' => '',
													'type' => 'tab',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'placement' => 'top',
													'endpoint' => 0,
												),
												array(
													'key' => 'field_5cc855105bab7',
													'label' => 'Content',
													'name' => 'content',
													'type' => 'textarea',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'maxlength' => '',
													'rows' => '',
													'new_lines' => '',
												),
												array(
													'key' => 'field_5cc855105bab8',
													'label' => 'Block Settings',
													'name' => '',
													'type' => 'tab',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'placement' => 'top',
													'endpoint' => 0,
												),
												array(
													'key' => 'field_5cc855105bab9',
													'label' => 'ID',
													'name' => 'block_id',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_5cc855105baba',
													'label' => 'Classes',
													'name' => 'block_class',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_5cc855105babb',
													'label' => 'Width',
													'name' => 'block_width',
													'type' => 'range',
													'instructions' => 'width in columns',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'min' => '',
													'max' => 12,
													'step' => 1,
													'prepend' => '',
													'append' => '',
												),
												array(
													'key' => 'field_5cc855105babc',
													'label' => 'Vertical Alignment',
													'name' => 'v_align',
													'type' => 'select',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'choices' => array(
														'top' => 'top',
														'middle' => 'middle',
														'bottom' => 'bottom',
													),
													'default_value' => array(
													),
													'allow_null' => 1,
													'multiple' => 0,
													'ui' => 1,
													'ajax' => 0,
													'return_format' => 'value',
													'placeholder' => '',
												),
												array(
													'key' => 'field_5cc855105babd',
													'label' => 'Center Content',
													'name' => 'center_content',
													'type' => 'true_false',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '25',
														'class' => '',
														'id' => '',
													),
													'message' => '',
													'default_value' => 0,
													'ui' => 1,
													'ui_on_text' => '',
													'ui_off_text' => '',
												),
											),
										),
									),
									'min' => '',
									'max' => '',
								),
							),
							'button_label' => 'Add Block',
							'min' => '',
							'max' => '',
						),
						array(
							'key' => 'field_5c5a04763727e',
							'label' => 'Section Settings',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5c55ce5b281cc',
							'label' => 'Section ID',
							'name' => 'section_id',
							'type' => 'text',
							'instructions' => 'Section id (without #)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => 30,
						),
						array(
							'key' => 'field_5c55ce92281cd',
							'label' => 'Section Classes',
							'name' => 'section_class',
							'type' => 'text',
							'instructions' => 'Section classes (seperate with a space)',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5c55bd4711eb4',
							'label' => 'Full Width',
							'name' => 'full_width',
							'type' => 'true_false',
							'instructions' => 'Make content full width?',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5c57411bbdac2',
							'label' => 'Vertical Align',
							'name' => 'vertical_align',
							'type' => 'true_false',
							'instructions' => 'Vertical align columns',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5c55bce011eb3',
							'label' => 'Section Background Image',
							'name' => 'section_background_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => 'jpg, png',
						),
						array(
							'key' => 'field_5c55c3f09c196',
							'label' => 'Section Background Color',
							'name' => 'section_background_color',
							'type' => 'color_picker',
							'instructions' => 'Pick a colour',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'transparent',
						),
						array(
							'key' => 'field_5c5630e4b6860',
							'label' => 'Use Overlay?',
							'name' => 'color_overlay',
							'type' => 'true_false',
							'instructions' => 'Use background color as overlay',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'flex-template.php',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
